### ISSUE TITLE
Hyper parameter optimisation while training XLMR

### ISSUE THREAD

**Issue by janaab11** [skit-ai/dialogy#105]
**Is your feature request related to a problem? Please describe.**
Unusually high training loss with default hyper params. We need grid search, atleast

**Describe the solution you'd like**
We can integrate something like wandb - it handles these optimisations nicely

**Describe alternatives you've considered**
Simple transformers has its own support for grid search, but we night want to move away from the wrapper to the original huggingface library (transformers)

**Comment by ltbringer** [comment]
We will do this over kubeflow
