### ISSUE TITLE
Behaviour of set_value() not same between BaseEntity and TimeIntervalEntity

### ISSUE THREAD

**Issue by oyoot** [skit-ai/dialogy#109]
**Describe the bug**
calling set_value on an object of BaseEntity will give us this structure
```{"values": [{"value": value of ent}]}```
but with TimeIntervalEntity, it gives us this structure
```{"values": [{"from": from-value, "to": to-value}]}```

**Expected behavior**
```ent["values"][0]["value"]``` should not result in KeyError for any entity

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Python version 3.8

**Comment by ltbringer** [comment]
Resolved in 0.9.3 onwards.
