### ISSUE TITLE
Edit ListEntityPlugin such that it extracts patterns from cls_feature instead of alternatives

### ISSUE THREAD

**Issue by nvinayvarma189** [skit-ai/dialogy#144]
**Is your feature request related to a problem? Please describe.**
Yes.

I want to write a custom plugin to apply some transformations to the ASR transcriptions. It is much easier for me to work with the `clf_feature` (as it is a simple list of strings) rather than `alternatives`( can be List[List[Dict[str, Any]]], List[Dict[str, Any]], List[str] or str). However, ListEntityPlugin takes the alternatives as input. So the entities will be extracted from the original input instead of the transformed input.

**Describe the solution you'd like**
Edit ListEntityPlugin such that it extracts patterns from cls_feature instead of alternatives. This will help writing transcription transformations easier.

**Describe alternatives you've considered**
Currently, I'm editing the alternatives themselves

**Additional context**
No.

**Comment by ltbringer** [comment]
We would hope to have better LM tuning tools so that ASR transcript tweaks become an afterthought :)
